### ISSUE TITLE
ico_detail页面Q&A排序功能实现

### ISSUE THREAD

**Issue by aero101** [IPQuan/webpages#10]
Q&A页面有个排序功能未实现，就是在作者回复&编辑一个问题时，可以给当前问题排序。作者在回复或者编辑状态下，序号变成星号，提示一直出现，不用鼠标悬停，点击星号可以输入数字，该问题出现在新输入序号的排序处。
![e9d0a0e2-65f9-4b0e-9977-81ec19e38697](https://cloud.githubusercontent.com/assets/8524980/23846580/0adfc48e-0809-11e7-9fd6-2ee5c9aa60f9.png)

**Comment by Liza491646703** [comment]
已完成。

**Comment by Liza491646703** [comment]
有问题：假设选中了排序，修改成18之后，此时还处于作者回复&编辑一个问题的状态还能连续修改排序数值吗？这个修改好的数值是修改即保存，还是点击了发送之后再进行保存？
