### ISSUE TITLE
导航栏 在800像素左右折叠问题

### ISSUE THREAD

**Issue by aero101** [IPQuan/webpages#11]
请消除折叠，考虑压缩字距或者缩短搜索栏，输入搜索内容时再恢复原长度
![fdfdc5b1-215b-4193-8bd8-263bacc1b76b](https://cloud.githubusercontent.com/assets/8524980/23846745/e0dd4430-0809-11e7-9ce0-5173db5da961.png)

**Comment by chenzhitong** [comment]
已修复，请核实。
可以在这里看到效果：[ipquan.azurewebsites.net](http://ipquan.azurewebsites.net/project_create.html)
