### ISSUE TITLE
字体问题

### ISSUE THREAD

**Issue by chenzhitong** [IPQuan/webpages#13]
如图，首页上的字体是苹方字体，但在Windows下没有苹方字体的时候就会默认显示宋体，字体变得比较难看。

<img width="893" alt="image" src="https://cloud.githubusercontent.com/assets/6295602/23957917/88803daa-09db-11e7-9ed4-40b55aa4c671.png">

[onchain.com](http://www.onchain.com) 的字体是

` font-family: "PingFangSC-Regular","PingHei","Lucida Grande","Lucida Sans Unicode","STHeitiSC-Light",Helvetica,"BBAlpha Sans","S60 Sans","Hiragino Sans GB",Arial,"Microsoft YaHei","Verdana",SimHei,STXihei,SimSun,"WenQuanYi Micro Hei",sans-serif`

可以参考

**Comment by Woo-ing** [comment]
@chenzhitong @aero101 是否可以根据操作系统选择不同的字体？
