### ISSUE TITLE
ico_invest页面下拉菜单比特币图标没有显示

### ISSUE THREAD

**Issue by aero101** [IPQuan/webpages#17]
如题
![wx20170319-083108](https://cloud.githubusercontent.com/assets/8524980/24101452/5aaf5024-0db3-11e7-863d-f9ad96d81197.png)

**Comment by aero101** [comment]
如果不支持iconfont，可以考虑用svg来实现

**Comment by Liza491646703** [comment]
已经使用模拟select框修改。
