### ISSUE TITLE
跨界基因没有链接（by Karol）

### ISSUE THREAD

**Issue by KKKarol-K** [IPQuan/webpages#53]
# 首页
## “开始了解“下面的小项可以考虑加上链接，能从图标上能直接点到下面每项相应的页面。
<img width="1005" alt="2017-05-25 2 41 07" src="https://cloud.githubusercontent.com/assets/28890758/26439109/2e0e59d2-4159-11e7-963e-09722dd73eaa.png">

## “团队的跨界基因”这个小标题和上面三个格式连不上。
<img width="1038" alt="2017-05-25 2 52 23" src="https://cloud.githubusercontent.com/assets/28890758/26439254/f286bb2e-4159-11e7-8195-36ecd6618e1e.png">

**Comment by Woo-ing** [comment]
图标和标签已加上链接，跨界基友字样没改，改了可能影响布局
