### ISSUE TITLE
ico_summary_B&ico_detail ICO卡片样式没有统一

### ISSUE THREAD

**Issue by aero101** [IPQuan/webpages#8]
如题，项目ICO卡片样式应该是一致的，或许是我UI定稿的时候没有和前端交互好，请 @Liza491646703 修改，谢谢！
![screen shot 2017-03-13 at 3 34 45 pm](https://cloud.githubusercontent.com/assets/8524980/23845379/a971caa4-0802-11e7-9828-6d82830b6ff2.png)

**Comment by aero101** [comment]
![wx20170313-153923](https://cloud.githubusercontent.com/assets/8524980/23845485/61fe1c1c-0803-11e7-9b77-7e6400dd3d26.png)

**Comment by Liza491646703** [comment]
已修复
